server:
  port: 8000

web:
  domain: http://localhost


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doubao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: baibing123
